Support RETURN AS in SEARCH
RediSearch/redisearch-go pull request #119
Opened 2021-07-18 11:05 UTC by AvitalFineRedis

2021-07-21 08:15 UTC, AvitalFineRedis commented
@chayim Why the codecov says I didn't cover these methods?

2021-07-27 07:40 UTC, chayim commented on Makefile
> +	@docker run --name redisearch-go-tests -d --rm -p 6379:6379 redislabs/redisearch:edge
The name of the docker should be in a variable.

2021-07-27 07:40 UTC, chayim commented on Makefile
> +	@docker stop redisearch-go-tests
Dockername in variable

2021-07-27 07:42 UTC, chayim commented on redisearch/query.go
> +func (q *Query) AddReturnFields(fields ...string) *Query {
Take a look at this for great doc foo. https://github.com/googleapis/googleapis/blob/master/google/api/http.proto

2021-07-27 07:43 UTC, chayim requested changes
Tiny changes requested.

2021-07-27 11:06 UTC, chayim approved these changes

2021-07-27 11:07 UTC, merged